### ISSUE TITLE
Handle a deleted top comment

### ISSUE THREAD

**Issue by johngodley** [hlashbrooke/The-Final-Word#9]
We recently ran into a situation where a P2 post wasn't being displayed. After investigation it was caused because a comment had been promoted to be the top comment, but had then since been deleted. There is no check in the code for the existence of the comment, and so P2 was fed an empty comment. Unfortunately P2 doesn't handle this well, and it results in the post not rendering at all.

https://github.com/hlashbrooke/The-Final-Word/blob/master/the-final-word.php#L244

**Comment by hlashbrooke** [comment]
Ooh - good catch. It looks like `get_comment()` returns `null` if no comment exists, so a simple `is_null()` check should fix that. I'll work on that now.

**Comment by hlashbrooke** [comment]
Fixed, tested and confirmed.

**Comment by johngodley** [comment]
Speedy! Thanks Hugh
